on:
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup pnpm
        uses: pnpm/setup@v2
        with:
          version: 12
          cache: true

      - name: Check
        run: pnpm biome ci

      - name: Test
        run: pnpm run test

      - name: Build
        run: pnpm run build
